// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class AppUsers
{
    public Guid Id { get; set; }

    public string UserName { get; set; }

    public byte[] PasswordHash { get; set; }

    public Guid? RoleId { get; set; }

    public Guid? DepartmentId { get; set; }

    public byte[] FullNameEnc { get; set; }

    public byte[] EmailEnc { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual Departments Department { get; set; }

    public virtual ICollection<Encounters> Encounters { get; set; } = new List<Encounters>();

    public virtual Roles Role { get; set; }

    public virtual ICollection<ScannedMedicalRecords> ScannedMedicalRecords { get; set; } = new List<ScannedMedicalRecords>();
}