// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class AuditLog
{
    public long Id { get; set; }

    public DateTime At { get; set; }

    public Guid? UserId { get; set; }

    public string Action { get; set; }

    public string Entity { get; set; }

    public Guid? EntityId { get; set; }

    public bool Success { get; set; }

    public string Ip { get; set; }

    public string Details { get; set; }
}