// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class Consents
{
    public Guid Id { get; set; }

    public Guid PatientId { get; set; }

    public string ConsentType { get; set; }

    public DateTime GivenAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public byte[] ConsentDoc { get; set; }

    public virtual Patients Patient { get; set; }
}