// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class Departments
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<AppUsers> AppUsers { get; set; } = new List<AppUsers>();

    public virtual ICollection<Encounters> Encounters { get; set; } = new List<Encounters>();

    public virtual ICollection<Patients> Patients { get; set; } = new List<Patients>();
}