// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class Encounters
{
    public Guid Id { get; set; }

    public Guid PatientId { get; set; }

    public Guid? DepartmentId { get; set; }

    public Guid? ClinicianId { get; set; }

    public DateTime EncounterDate { get; set; }

    public byte[] NotesEnc { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public virtual AppUsers Clinician { get; set; }

    public virtual Departments Department { get; set; }

    public virtual Patients Patient { get; set; }
}