// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class Encounter
{
    public Guid Id { get; set; }

    public Guid PatientId { get; set; }

    public DateTime EncounterDate { get; set; }

    public byte[] NotesEnc { get; set; }

    public string Icd10codes { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Patient Patient { get; set; }
}