// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MedVault.Api.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MedVault.Api.Models
{
    public partial interface IMedVaultDbContextProcedures
    {
        Task<int> CallExternalApiAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SendEmailAsync(string recipientEmailAddress, string subject, string body, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
