// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MedVault.Api.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MedVault.Api.Models
{
    public partial class MedVaultDbContext
    {
        private IMedVaultDbContextProcedures _procedures;

        public virtual IMedVaultDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MedVaultDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMedVaultDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class MedVaultDbContextProcedures : IMedVaultDbContextProcedures
    {
        private readonly MedVaultDbContext _context;

        public MedVaultDbContextProcedures(MedVaultDbContext context)
        {
            _context = context;
        }

        public virtual async Task<int> CallExternalApiAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[CallExternalApi]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SendEmailAsync(string recipientEmailAddress, string subject, string body, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "RecipientEmailAddress",
                    Size = 640,
                    Value = recipientEmailAddress ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Subject",
                    Size = 510,
                    Value = subject ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Body",
                    Size = -1,
                    Value = body ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SendEmail] @RecipientEmailAddress = @RecipientEmailAddress, @Subject = @Subject, @Body = @Body", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
