// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MedVault.Api.Models;

public partial class MedVaultDbContext : DbContext
{
    public MedVaultDbContext(DbContextOptions<MedVaultDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AppUser> AppUsers { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Consent> Consents { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Encounter> Encounters { get; set; }

    public virtual DbSet<Patient> Patients { get; set; }

    public virtual DbSet<PatientIdentityDocument> PatientIdentityDocuments { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ScannedMedicalRecord> ScannedMedicalRecords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AppUsers__3214EC0759D48D78");

            entity.HasIndex(e => e.UserName, "UQ__AppUsers__C9F284564BCC9A22").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Department).WithMany(p => p.AppUsers)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_AppUsers_Department");

            entity.HasOne(d => d.Role).WithMany(p => p.AppUsers)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_AppUsers_Role");
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AuditLog__3214EC07E57D42FF");

            entity.ToTable("AuditLog");

            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.At).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Details).HasMaxLength(1000);
            entity.Property(e => e.Entity)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.Ip).HasMaxLength(64);
        });

        modelBuilder.Entity<Consent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Consents__3214EC0783C7553D");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ConsentType)
                .IsRequired()
                .HasMaxLength(80);

            entity.HasOne(d => d.Patient).WithMany(p => p.Consents)
                .HasForeignKey(d => d.PatientId)
                .HasConstraintName("FK_Consents_Patient");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC07E8346212");

            entity.HasIndex(e => e.Name, "UQ__Departme__737584F6553D6F57").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(120);
        });

        modelBuilder.Entity<Encounter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Encounte__3214EC07317AB236");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Icd10codes)
                .HasMaxLength(400)
                .HasColumnName("ICD10Codes");

            entity.HasOne(d => d.Patient).WithMany(p => p.Encounters)
                .HasForeignKey(d => d.PatientId)
                .HasConstraintName("FK_Encounters_Patient");
        });

        modelBuilder.Entity<Patient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Patients__3214EC07C5F73F0F");

            entity.HasIndex(e => e.MedicalRecordNumber, "UQ__Patients__8E549ED00132E7D0").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FirstNameEnc).IsRequired();
            entity.Property(e => e.JmbgHmac)
                .IsRequired()
                .HasMaxLength(32)
                .IsFixedLength();
            entity.Property(e => e.Jmbgenc)
                .IsRequired()
                .HasColumnName("JMBGEnc");
            entity.Property(e => e.LastNameEnc).IsRequired();
            entity.Property(e => e.LastNameHmac)
                .IsRequired()
                .HasMaxLength(32)
                .IsFixedLength();
            entity.Property(e => e.MedicalRecordNumber)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Department).WithMany(p => p.Patients)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_Patients_Dep");
        });

        modelBuilder.Entity<PatientIdentityDocument>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PatientI__3214EC071ABB2B86");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DocNumberEnc).IsRequired();
            entity.Property(e => e.DocType)
                .IsRequired()
                .HasMaxLength(40);

            entity.HasOne(d => d.Patient).WithMany(p => p.PatientIdentityDocuments)
                .HasForeignKey(d => d.PatientId)
                .HasConstraintName("FK_PatientIdentityDocuments_Patient");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC07A4D4A137");

            entity.HasIndex(e => e.Name, "UQ__Roles__737584F604C221BC").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(32);
        });

        modelBuilder.Entity<ScannedMedicalRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ScannedM__3214EC07BACF1599");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Blob).IsRequired();
            entity.Property(e => e.ContentType)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.OriginalFileName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.RecordType)
                .IsRequired()
                .HasMaxLength(40);

            entity.HasOne(d => d.Patient).WithMany(p => p.ScannedMedicalRecords)
                .HasForeignKey(d => d.PatientId)
                .HasConstraintName("FK_ScannedMedicalRecords_Patient");

            entity.HasOne(d => d.UploadedByNavigation).WithMany(p => p.ScannedMedicalRecords)
                .HasForeignKey(d => d.UploadedBy)
                .HasConstraintName("FK_ScannedMedicalRecords_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}