// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class PatientIdentityDocuments
{
    public Guid Id { get; set; }

    public Guid PatientId { get; set; }

    public string DocType { get; set; }

    public byte[] DocNameEnc { get; set; }

    public byte[] IssueDateEnc { get; set; }

    public byte[] ExpiryDateEnc { get; set; }

    public byte[] ScanBlob { get; set; }

    public DateTime CreatedAt { get; set; }

    public string ContentType { get; set; }

    public byte[] OriginalFileNameEnc { get; set; }

    public virtual Patients Patient { get; set; }
}