// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class Patient
{
    public Guid Id { get; set; }

    public string MedicalRecordNumber { get; set; }

    public byte[] LastNameEnc { get; set; }

    public byte[] FirstNameEnc { get; set; }

    public byte[] Jmbgenc { get; set; }

    public byte[] AddressEnc { get; set; }

    public byte[] PhoneEnc { get; set; }

    public byte[] EmailEnc { get; set; }

    public byte[] LastNameHmac { get; set; }

    public byte[] JmbgHmac { get; set; }

    public Guid? DepartmentId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Consent> Consents { get; set; } = new List<Consent>();

    public virtual Department Department { get; set; }

    public virtual ICollection<Encounter> Encounters { get; set; } = new List<Encounter>();

    public virtual ICollection<PatientIdentityDocument> PatientIdentityDocuments { get; set; } = new List<PatientIdentityDocument>();

    public virtual ICollection<ScannedMedicalRecord> ScannedMedicalRecords { get; set; } = new List<ScannedMedicalRecord>();
}