// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class Patients
{
    public Guid Id { get; set; }

    public string MedicalRecordNumber { get; set; }

    public byte[] LastNameEnc { get; set; }

    public byte[] FirstNameEnc { get; set; }

    public byte[] JMBGEnc { get; set; }

    public byte[] AddressEnc { get; set; }

    public byte[] PhoneEnc { get; set; }

    public byte[] EmailEnc { get; set; }

    public byte[] LastNameHmac { get; set; }

    public byte[] JmbgHmac { get; set; }

    public Guid? DepartmentId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Consents> Consents { get; set; } = new List<Consents>();

    public virtual Departments Department { get; set; }

    public virtual ICollection<Encounters> Encounters { get; set; } = new List<Encounters>();

    public virtual ICollection<PatientIdentityDocuments> PatientIdentityDocuments { get; set; } = new List<PatientIdentityDocuments>();

    public virtual ICollection<ScannedMedicalRecords> ScannedMedicalRecords { get; set; } = new List<ScannedMedicalRecords>();
}