// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedVault.Api.Models;

public partial class ScannedMedicalRecords
{
    public Guid Id { get; set; }

    public Guid PatientId { get; set; }

    public string RecordType { get; set; }

    public string OriginalFileName { get; set; }

    public string ContentType { get; set; }

    public long OriginalLength { get; set; }

    public int PaddingLength { get; set; }

    public byte[] Blob { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? UploadedBy { get; set; }

    public virtual Patients Patient { get; set; }

    public virtual AppUsers UploadedByNavigation { get; set; }
}